name = "ffa-comparateur-api"
main = "worker.js"
compatibility_date = "2026-08-31"
preview_urls = false
# ranking filters and column sorting use precomputed D1 ranks

[[d1_databases]]
binding = "DB"
database_name = "ffa-comparateur"
database_id = "110af62a-034e-471d-ae99-53971c754f7b"
